### PR TITLE
Update USB DSD kernel with more device quirks

### PR DESCRIPTION
**Pull request by paolosabatino**
As per subject: kernel has recompiled importing more quirks from mainline kernel and modules have been rebuilt also.

### CODE REVIEW

**Comment by gkkpch** [comment]
Could you also update the linux-mp1 kernel repo please, so we can see the quirks.c patches?

**Comment by volumio** [comment]
@gkkpch could you please point out which vid shall we preserve here? Thanks!

**Comment by gkkpch** [comment]
Hi,

that should be vid 0x22e8, manufacturer CamBridge in block
"/* Mostly generic method to detect many DSD-capable implementations -
	 * from XMOS/Thesycon
	 */"

**Comment by gkkpch** [comment]
Paolo, I will write a complete quirks entry tomorrow for you.

**Comment by paolosabatino** [comment]
I integrate the usb-audio-* patches from [this](https://github.com/paolosabatino/platform-khadas/tree/master/kernel-4.9.206) directory into linux-mp1/khadas-4.9.241-earc with [this](https://github.com/volumio/linux-mp1/commit/512c2b11ae8bc7ecfbd892cbdb642f3a2e697664) other commit, but can't find anything with 0x22e8 manufacturer.

I will wait for the full list though, thanks!

**Pull request merged**
